services:
  backend:
    build: .
    environment:
      - POSTGRES_CONN_STR=user=postgres password=password sslmode=disable host=db
    ports:
      - "8080:8080"

  db:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  pgdata:
