// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"
)

const listVideos = `-- name: ListVideos :many
SELECT id, name, youtube_id, created_at, status
FROM reorder.videos
ORDER BY created_at DESC
`

func (q *Queries) ListVideos(ctx context.Context) ([]ReorderVideo, error) {
	rows, err := q.db.Query(ctx, listVideos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReorderVideo
	for rows.Next() {
		var i ReorderVideo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.YoutubeID,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
